class point:
	"""Holds points generated by the GPX logger of dailyroads"""
	def __init__(self,idx):
		self.index = idx
	def set_date(self,date):
		self.date = date
	def set_time(self,t):
		h,m,s = t.split(':')
		self.h = int(h)
		self.m = int(m)
		self.s = int(s)
		self.t = t
	def set_latitude(self,lat):
		self.lat = lat
	def set_longitude(self,lon):
		self.lon = lon
	def set_altitude(self,alt):
		self.alt = alt
	def set_speed(self,spd):
		self.spd = spd
	def get_time(self):
		return self.h * 3600 + self.m * 60 + self.s

def read_from_srt(filename):
	gps = []
	with open(filename) as myfile:
		for line in myfile:
			if len(line.split())==0:
				continue
			if line.rstrip().isdigit():
				gp = point(int(line))
				continue
			if line.split(':')[0].isdigit():
				continue
			if line.split()[-1]=='m':
				ss = line.split()
				if ss[0].isdigit():
					gp.set_speed(float(ss[0]))
				gp.set_date(ss[2])
				gp.set_time(ss[3])
				if ss[4].isdigit():
					gp.set_altitude(float(ss[4]))
				continue
			if line.split()[0]=='lat:':
				ss = line.split()
				gp.set_latitude(float(ss[1]))
				gp.set_longitude(float(ss[3]))
				gps.append(gp)
	return gps